# Конфигурационный файл worker
app:
  log:
    enabled: true
    trap: false

# Engine settings
engine:
  # Projects pathes for components searchig like files, payloads etc
  projects:
  - ./
  - ../default
  # default arguments
  default:
    # For undefined route will be use followng route
    route-name: make

# Web settings 
web:

  default:
    # default context
    context: [ default ]

  # Session settings
  session:
    # Disable or enable session 
    enabled: false
    # Time to live for session cookie
    ttl-sec: 86400
    # This is default secure key
    ssl-key: MySecureKey

  # Маршрутизация запросов worker
  rules:
    # из локальной подсети
    "127.0.0.0/8":
      # входящий на любой порт
      "*":
        # для любого сайта
        "*":
          # пустая ссылка
          "/":
            # уходит на вывод контента
            uri: /content/page/main.html
            trace: true
          "*":
            # иначе выполняется как есть 
            # с трассировкой
            trace: true
    # со всех инфх адресов
    "0.0.0.0/0":
      # для всех портов
      "*":
        # для всех хостов
        "*":
          # любая ссылка
          "*":
            # уходит в ошибку
            action: error/error404
            # без трассировки
            trace: false

  # Механизм вызова удаленных полезных нагрузок
  summon:
    # Возможность локального вызова если полезная нагрузка доступна 
    prefer-local: false
    # Количество попыток вызова пэйлоада при отказе
    try: 4
    # Хосты по которым потенциально будут осуществляеться вызовы
    # protocol://[user[:password]@]host[:port]
    hosts:
    - http://127.0.0.1:42011
    # Предельное время исполнения запроса
    # payload[/method]|*
    request-timeout-mls:
      "*": 1000
    # Предельное время подклюения к хосту
    # payload[/method]|*
    connect-timeout-mls:
      "*": 1000

  # options for cli starting with `php index.php`
  cli:
    # url for cli mode
    url: http://localhost
